<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Chi Dao">
<meta name="author" content="I Putu Agastya Harta Pratama">
<meta name="author" content="Si Tang Lin">
<meta name="author" content="Zuzanna Uljasz">
<meta name="dcterms.date" content="2026-06-01">

<title>Sentiment Analysis of Mobile Banking App Reviews</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="report_2_files/libs/clipboard/clipboard.min.js"></script>
<script src="report_2_files/libs/quarto-html/quarto.js"></script>
<script src="report_2_files/libs/quarto-html/popper.min.js"></script>
<script src="report_2_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="report_2_files/libs/quarto-html/anchor.min.js"></script>
<link href="report_2_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="report_2_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="report_2_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="report_2_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="report_2_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="report_2.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Sentiment Analysis of Mobile Banking App Reviews</h1>
<p class="subtitle lead">A Reproducible Study: R to Python, Old Data to New Data, Lexicon to Transformer</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Authors</div>
    <div class="quarto-title-meta-contents">
             <p>Chi Dao </p>
             <p>I Putu Agastya Harta Pratama </p>
             <p>Si Tang Lin </p>
             <p>Zuzanna Uljasz </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">June 1, 2026</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="summary" class="level1">
<h1>Summary</h1>
<p>This report documents a reproducible research project that translates an original R-based sentiment analysis of mobile banking app reviews into Python, extends it with newly scraped data, and augments the lexicon-based methods with a transformer (BERT) approach. The project covers five major US banks: Bank of America, Chase, Citi, Marcus by Goldman Sachs, and Wells Fargo across the Apple App Store (iOS) and Google Play (Android). The core research questions are: (1) Can the original R findings be faithfully reproduced in Python? (2) Do the results change with a fresh data scrape? (3) Does a transformer model produce sentiment classifications consistent with the lexicon approach?</p>
</section>
<section id="introduction-and-motivation" class="level1">
<h1>1. Introduction and Motivation</h1>
<section id="research-context" class="level2">
<h2 class="anchored" data-anchor-id="research-context">1.1 Research Context</h2>
<p>Customer reviews on mobile app stores represent a rich, continuously updated source of unstructured opinion data. For the banking sector, app reviews offer direct evidence of customer satisfaction, pain points, and competitive positioning — feedback that often offers a faster point of view and is more granular than traditional survey methods. Sentiment analysis of these reviews can help researchers and practitioners understand how user experience varies across institutions and platforms, and whether negative signals co-occur with specific feature complaints or rating patterns.</p>
<p>There are two motivations for this study. Academically, it provides an opportunity to practice reproducible research: taking an existing empirical study, replicating it in a different computational environment, and evaluating whether the results remain the same. Practically, it investigates whether mobile banking sentiment has shifted between the original data collection window and a fresh scrape in 2026, and whether more sophisticated deep learning methods agree with classic dictionary-based approaches.</p>
</section>
<section id="inspiration-and-source-study" class="level2">
<h2 class="anchored" data-anchor-id="inspiration-and-source-study">1.2 Inspiration and Source Study</h2>
<p>The project is inspired by the tidytext-based workflow popularised by <span class="citation" data-cites="silge2017text">Silge and Robinson (<a href="#ref-silge2017text" role="doc-biblioref">2017</a>)</span>, which applies lexicon-based sentiment scoring to tokenised text in a tidy data format. The original analysis follows this approach: it imports and cleans review data, performs unigram sentiment analysis using three lexicons (Bing, AFINN, NRC), constructs bigrams with negator-aware scoring, and evaluates results statistically. The goal of this project is to demonstrate that these findings are reproducible — the same pipeline, implemented in Python with equivalent libraries, produces consistent conclusions — and then to extend the study in two directions: new data and a transformer model.</p>
</section>
</section>
<section id="data" class="level1">
<h1>2. Data</h1>
<p>Dataset is obtained with the means of scrapping reviews from the App Store and Google Play for the five major banks in US. The original dataset was collected in 2023, while the new dataset was scraped in mid-2026. Both datasets contain reviews in English, with metadata including star ratings, review text, date, platform, and storefront. The data is stored as CSV files per bank and platform, which are combined and preprocessed for analysis.</p>
<p>The major banks included in the dataset are some of the largest US financial institutions, which are: Bank of America, Chase, Citi, Marcus by Goldman Sachs, and Wells Fargo. Each has a significant mobile banking user base. The platforms covered are the two dominant mobile ecosystems: Apple’s App Store (iOS) and Google’s Play Store (Android). This allows for cross-platform comparisons and insights into whether user sentiment differs by operating system.</p>
<p>The method of scrapping differs for each platform due to their distinct APIs and structures. For the iOS App Store, the script uses Python’s requests library to directly parse Apple’s publicly accessible XML/JSON RSS feed endpoints, which are ordered by the most recent submissions. For the Google Play Store, it leverages an open-source web scraping library (google-play-scraper) that mimics browser requests to dynamically fetch and page through raw review payloads using continuation tokens. Both approaches process these external data streams in real time, converting the raw JSON responses into structured Pandas DataFrames before exporting them to CSV files.</p>
<section id="exploratory-data-analysis-of-the-original-dataset-old-data" class="level2">
<h2 class="anchored" data-anchor-id="exploratory-data-analysis-of-the-original-dataset-old-data">2.1 Exploratory Data Analysis of the Original Dataset (Old Data)</h2>
<p>The original dataset was collected in 2025 using a combination of web scraping and API access methods. It includes reviews from the same five banks and both platforms, but covers a different time period than the new data. The dataset is stored as CSV files, one per bank and platform, with columns for review text, star rating, date, and other metadata. The original analysis applied lexicon-based sentiment scoring to this dataset to derive insights about user sentiment and its relationship to star ratings.</p>
<div id="fig-eda-rating-old" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="plots/rating_dist_platform_old.png" class="img-fluid figure-img" style="width:95.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;1: Rating distribution by platform — older dataset (raw data)</figcaption>
</figure>
</div>
<p>The raw rating distribution across platforms in the older dataset reveals a consistent J-shaped pattern, where 1-star and 5-star reviews dominate across all four platforms (<a href="#fig-eda-rating-old">Figure&nbsp;1</a>). Android and iOS show the largest review volumes overall, with Android having approximately 3,000 five-star reviews and around 1,000 one-star reviews, while iOS shows a more balanced split between the two extremes with roughly 2,000 one-star and 1,500 five-star reviews. The app_store and google_play platforms follow a similar J-shaped pattern but at lower volumes, each contributing around 1,000 reviews at both the 1-star and 5-star ends. Mid-range ratings of 2, 3, and 4 stars are consistently sparse across all platforms, which is a common characteristic of app store review data where users tend to leave reviews only when strongly satisfied or dissatisfied.</p>
<table class="table">
<thead>
<tr class="header">
<th>Statistic</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>count</td>
<td>14,485</td>
</tr>
<tr class="even">
<td>mean</td>
<td>8.63</td>
</tr>
<tr class="odd">
<td>std</td>
<td>21.80</td>
</tr>
<tr class="even">
<td>min</td>
<td>0.0</td>
</tr>
<tr class="odd">
<td>25%</td>
<td>0.0</td>
</tr>
<tr class="even">
<td>50%</td>
<td>0.0</td>
</tr>
<tr class="odd">
<td>75%</td>
<td>6.0</td>
</tr>
<tr class="even">
<td>max</td>
<td>411.0</td>
</tr>
</tbody>
</table>
<p>The raw review texts in the older dataset are notably short on average, with a mean of 8.63 words and a median of 0.0, indicating that the majority of reviews contain no text at all and consist only of a star rating. Among reviews that do contain text, length varies considerably, ranging from a single word up to 411 words with a standard deviation of 21.80.</p>
</section>
<section id="exploratory-data-analysis-of-the-new-dataset-new-data" class="level2">
<h2 class="anchored" data-anchor-id="exploratory-data-analysis-of-the-new-dataset-new-data">2.2 Exploratory Data Analysis of the New Dataset (New Data)</h2>
<p>The new dataset was collected using a dedicated scraper (<code>Dataset/scraper.ipynb</code>) targeting the same five banks and both platforms. The scraping window covers a more recent period - <em>early 2026</em>. While the column structure is identical to the old dataset, the new data captures a different temporal slice of user opinions and may reflect changes in app features, service quality, or competitive dynamics that occurred after the original collection window. Upon checking, the rating distribution of the new data is similar to the original one, with the majority of reviews are at extreme positions, either 1 or 5 stars (<strong>?@fig-star-dist-new</strong>).</p>
<div id="fig-eda-rating-new" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="plots/rating_dist_platform_new.png" class="img-fluid figure-img" style="width:90.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;2: Rating distribution by platform — newer dataset (raw data)</figcaption>
</figure>
</div>
<p>The newer dataset contains only two platforms, app_store and google_play, in contrast to the four platforms present in the older data (<a href="#fig-eda-rating-old">Figure&nbsp;1</a> and <a href="#fig-eda-rating-new">Figure&nbsp;2</a>). Both platforms follow the same J-shaped pattern seen previously, with google_play showing a more pronounced positive skew, approximately 2,100 five-star reviews against 500 one-star reviews — while app_store shows a more balanced split of roughly 900 one-star and 1,200 five-star reviews.</p>
<table class="table">
<thead>
<tr class="header">
<th>Statistic</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>count</td>
<td>5,450</td>
</tr>
<tr class="even">
<td>mean</td>
<td>22.04</td>
</tr>
<tr class="odd">
<td>std</td>
<td>29.05</td>
</tr>
<tr class="even">
<td>min</td>
<td>1.0</td>
</tr>
<tr class="odd">
<td>25%</td>
<td>4.0</td>
</tr>
<tr class="even">
<td>50%</td>
<td>11.0</td>
</tr>
<tr class="odd">
<td>75%</td>
<td>28.0</td>
</tr>
<tr class="even">
<td>max</td>
<td>377.0</td>
</tr>
</tbody>
</table>
<p>Unlike the older dataset, the newer data contains no empty reviews, with a minimum length of 1 word and a median of 11 words, suggesting the newer collection was filtered to retain only reviews with actual text. Review length still varies considerably, ranging up to 377 words with a mean of 22.04 and a standard deviation of 29.05.</p>
</section>
<section id="data-preprocessing" class="level2">
<h2 class="anchored" data-anchor-id="data-preprocessing">2.3 Data Preprocessing</h2>
<section id="data-preprocessing-for-lexicon-based-methods" class="level3">
<h3 class="anchored" data-anchor-id="data-preprocessing-for-lexicon-based-methods">2.3.1 Data Preprocessing for Lexicon-Based Methods</h3>
<p>Preprocessing follows the same logical steps in both the R original and the Python replications:</p>
<ol type="1">
<li><strong>Import and combine</strong> — per-bank CSV files are loaded and concatenated into a single dataframe, with a <code>source_file</code> column added to retain the origin filename.</li>
<li><strong>Bank and platform name standardisation</strong> — bank names are extracted from filenames by stripping the <code>__combined_us.csv</code> suffix and converting underscores to title case; platform codes are mapped from <code>app_store</code> → <code>iOS</code> and <code>google_play</code> → <code>Android</code>.</li>
<li><strong>Type coercion</strong> — <code>rating</code> is cast to numeric and <code>date</code> is parsed to datetime, with invalid values coerced to <code>NaN</code>.</li>
<li><strong>Raw text construction</strong> — the <code>title</code> and <code>review</code> fields are concatenated into a single <code>raw_text</code> column, with missing values filled as empty strings.</li>
<li><strong>Language detection</strong> — <code>langdetect</code> is applied to <code>raw_text</code> with a fixed seed (<code>DetectorFactory.seed = 0</code>) for reproducibility; only reviews detected as English (<code>"en"</code>) are retained.</li>
<li><strong>Tokenisation and stopword removal</strong> — text is lowercased and tokenised using the regex pattern <code>\b[a-z]+\b</code>; a custom stopword list combining scikit-learn’s <code>ENGLISH_STOP_WORDS</code> with eight domain-specific terms (<em>app, bank, banking, mobile, iphone, apple, android, phone</em>) is applied.</li>
<li><strong>Lemmatisation</strong> <em>(old data only)</em> — tokens are lemmatised using NLTK’s <code>WordNetLemmatizer</code> with POS-aware tagging, mapping adjectives, verbs, nouns, and adverbs to their base forms before sentiment matching.</li>
<li><strong>Bigram construction</strong> <em>(new data only)</em> — adjacent word pairs are extracted from <code>raw_text</code> using a separate stopword list that explicitly excludes 25 negators (<em>no, not, never, cannot</em>, etc.) so they are preserved in bigrams for downstream negation correction.</li>
</ol>
</section>
<section id="data-preprocessing-for-transformer-methods" class="level3">
<h3 class="anchored" data-anchor-id="data-preprocessing-for-transformer-methods">2.3.2 Data Preprocessing for Transformer Methods</h3>
<p>For the transformer approach, an additional cleaning step keeps punctuation intact (since BERT tokenisers handle it natively) and removes URLs, which includes:</p>
<p>Preprocessing for the transformer-based method follows these steps, applied identically to both the original and new datasets:</p>
<ol type="1">
<li><strong>Emoji demojization</strong> — emojis are converted to their text equivalents using the <code>emoji.demojize()</code> function, preserving the semantic content of emoji-heavy reviews rather than discarding it.</li>
<li><strong>Lowercasing</strong> — all text is converted to lowercase for consistency.</li>
<li><strong>URL removal</strong> — HTTP and WWW URLs are stripped using regex (<code>http\S+|www\S+</code>).</li>
<li><strong>HTML tag removal</strong> — any HTML tags are removed using regex (<code>&lt;.*?&gt;</code>).</li>
<li><strong>Unicode cleaning</strong> — non-printable and special unicode characters are filtered out by removing characters whose unicode category falls in <code>So</code>, <code>Cs</code>, <code>Co</code>, or <code>Cn</code>.</li>
<li><strong>Repeated character normalisation</strong> — sequences of three or more identical characters are collapsed to two (e.g.&nbsp;<em>sooooo</em> → <em>soo</em>), reducing noise from informal writing.</li>
<li><strong>Punctuation removal</strong> — all non-word, non-whitespace characters are stripped, keeping only alphanumeric tokens and spaces.</li>
<li><strong>Whitespace normalisation</strong> — multiple consecutive spaces are collapsed to a single space and leading/trailing whitespace is removed.</li>
</ol>
</section>
</section>
</section>
<section id="methodology" class="level1">
<h1>3. Methodology</h1>
<section id="lexicon-based-sentiment-analysis" class="level2">
<h2 class="anchored" data-anchor-id="lexicon-based-sentiment-analysis">3.1 Lexicon-Based Sentiment Analysis</h2>
<p>Three lexicons are applied to the filtered tokens. Scores are computed at the review level and disaggregated by bank and platform.</p>
<p><strong>Bing (Opinion Lexicon):</strong> A binary lexicon classifying words as positive or negative. Review sentiment is the count of positive words minus negative words.</p>
<p><strong>AFINN:</strong> An integer-scored lexicon (−5 to +5) <span class="citation" data-cites="nielsen2011new">(<a href="#ref-nielsen2011new" role="doc-biblioref">Nielsen 2011</a>)</span>. Review scores are the sum of matched word scores. Pearson correlation between AFINN scores and star ratings serves as a validity check.</p>
<p><strong>NRC Emotion Lexicon:</strong> Developed by <span class="citation" data-cites="mohammad2013crowdsourcing">Mohammad and Turney (<a href="#ref-mohammad2013crowdsourcing" role="doc-biblioref">2013</a>)</span>, this lexicon maps words to 8 emotion categories (anger, anticipation, disgust, fear, joy, sadness, surprise, trust) and 2 polarity categories. One word may belong to multiple categories, enabling nuanced emotion profiling.</p>
</section>
<section id="bigram-analysis-and-negation-correction" class="level2">
<h2 class="anchored" data-anchor-id="bigram-analysis-and-negation-correction">3.2 Bigram Analysis and Negation Correction</h2>
<p>Unigram methods cannot handle negation: <em>not good</em> is scored as positive because <em>good</em> carries a positive AFINN score. To quantify this limitation, bigrams are constructed from the raw review text, with negators explicitly retained in the stopword filter. A set of 22 negators is defined (e.g., <em>no</em>, <em>not</em>, <em>n’t</em>, <em>never</em>, <em>cannot</em>). Where the first token of a bigram is a negator and the second has an AFINN score, the score is sign-flipped. The magnitude of the resulting correction is reported by star-rating group.</p>
</section>
<section id="transformer-based-sentiment-analysis" class="level2">
<h2 class="anchored" data-anchor-id="transformer-based-sentiment-analysis">3.3 Transformer-Based Sentiment Analysis</h2>
<p>As a complement to the lexicon methods, the pre-trained model <code>nlptown/bert-base-multilingual-uncased-sentiment</code> <span class="citation" data-cites="nlptown2019">(<a href="#ref-nlptown2019" role="doc-biblioref">NLP Town 2019</a>)</span> is applied via the Hugging Face <code>transformers</code> pipeline. The model predicts a 1–5 star rating for each review; predictions are normalised to a continuous sentiment score:</p>
<p><span class="math display">\[\text{bert\_score} = \frac{\text{bert\_stars} - 1}{4} \in [0, 1]\]</span></p>
<p>Model validity is assessed by (1) Pearson correlation between <code>bert_score</code> and the actual star rating (95% CI via Fisher’s <em>z</em>-transformation), (2) boxplots of <code>bert_score</code> stratified by star rating, bank, and platform, (3) exact star-level agreement and a full confusion matrix, and (4) a Mann–Whitney U test comparing platform distributions.</p>
</section>
</section>
<section id="results" class="level1">
<h1>4. Results</h1>
<section id="results-python-vs-r" class="level2">
<h2 class="anchored" data-anchor-id="results-python-vs-r">4.1 Results Python vs R</h2>
<p>This section aims to answer the first research question of our study: <strong>Can the original R findings be faithfully reproduced in Python?</strong> The Python results are compared with the file <code>original-sentiment-analysis-report</code>, stored in the folder <code>original_r_report</code>. The project aimed to directly replicate the R results in Python. However, due to several methodological and technical limitations, full reproduction was not possible.</p>
<p><strong>Data Pre-processing</strong></p>
<p>The first differences appeared already at the data pre-processing stage, especially during language detection. The original R analysis used the function <code>cld3::detect_language(raw_text)</code>, which comes from the R package <code>cld3</code>. This function cannot be directly used in standard Python code because it belongs to the R ecosystem. Therefore, in the Python version, we used the <code>langdetect</code> package instead.</p>
<p>However, <code>langdetect</code> and R’s <code>cld3</code> are different language detection tools. They use different models and rules when classifying the language. As a result, Python identified 4,518 English reviews, while R’s <code>cld3</code> identified 4,213 English reviews. Since different tools had to be used, this part of the analysis could not be fully reproduced. In Python, only 17.1% of reviews were removed as non-English, while in R, 22.7% of reviews were treated as non-English and removed from the dataset.</p>
<p>This difference also affects the following stopword removal step. The R project used <code>tidytext::stop_words</code>, while the Python project used scikit-learn’s <code>ENGLISH_STOP_WORDS</code>. These stopword lists are not identical. This changes the token list before sentiment lexicon matching.</p>
<p>Tokenization methods also differ between the two workflows. R used <code>unnest_tokens()</code>, while Python used regular-expression-based tokenization. This limitation affected the number of tokens.</p>
<p>Lastly, we decided to extend the Python study by including lemmatization, which is a common technique in lexicon-based sentiment analysis. Lemmatization was not included in the original R preprocessing pipeline. We hoped that including this step will make our results more reliable compared to the R project, which skipped this part of data pre-processing.</p>
<p><strong>Bing Sentiment Analysis</strong></p>
<p>Both the R and Python plots show that positive Bing words appear more often than negative Bing words (<a href="#fig-r-bing-distribution">Figure&nbsp;3</a> and <a href="#fig-lexicon-old-bing-distribution">Figure&nbsp;4</a>). However, the difference between positive and negative words is much larger in the Python plot. In the original R version, the two bars are relatively close, while in the Python version the positive bar is almost twice as high as the negative bar. Python preprocessing kept or created more positive sentiment matches, especially after using a different stopword list and lemmatization.</p>
<div class="quarto-layout-panel" data-fig-pos="H">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-r-bing-distribution" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="plots/r_bing_distribution.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;3: Distribution of Bing Sentiment Words in R</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-lexicon-old-bing-distribution" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="plots/old_lexicon_bing_distribution.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;4: Distribution of Bing Sentiment Words in Python</figcaption>
</figure>
</div>
</div>
</div>
</div>
<p>Results show that most review-level Bing sentiment scores are close to zero or slightly positive (<a href="#fig-r-bing-review-lvl">Figure&nbsp;5</a> and <a href="#fig-lexicon-old-bing-review-lvl">Figure&nbsp;6</a>). The Python distribution is more concentrated around small positive values and has a wider range of extreme scores. The R version appears more spread around both negative and positive values. This suggests that the Python preprocessing may have increased positive matches at the review level.</p>
<div class="quarto-layout-panel" data-fig-pos="H">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-r-bing-review-lvl" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="plots/r_bing_review_lvl_sentiment.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;5: Distribution of Review-Level Bing Sentiment Scores in R</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-lexicon-old-bing-review-lvl" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="plots/old_lexicon_bing_review_lvl_sentiment.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;6: Distribution of Review-Level Bing Sentiment Scores in Python</figcaption>
</figure>
</div>
</div>
</div>
</div>
<p>Both versions reproduce the expected relationship between star rating and Bing sentiment score (<a href="#fig-r-bing-review-sentiment-star">Figure&nbsp;7</a> and <a href="#fig-lexicon-old-bing-sentiment-star">Figure&nbsp;8</a>). Lower-rated reviews generally have more negative sentiment scores, while higher-rated reviews have more positive sentiment scores. However, the Python plot shows slightly higher sentiment scores for 3-star reviews and a positive shift for 4- and 5-star reviews.</p>
<div class="quarto-layout-panel" data-fig-pos="H">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-r-bing-review-sentiment-star" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="plots/r_bing_review_sentiment_by_star.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;7: Review-Level Bing Sentiment Score by Star Rating in R</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-lexicon-old-bing-sentiment-star" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="plots/old_lexicon_bing_sentiment_by_star.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;8: Review-Level Bing Sentiment Score by Star Rating in Python</figcaption>
</figure>
</div>
</div>
</div>
</div>
<p><strong>AFINN Sentiment Analysis</strong></p>
<p>The bank and platform plot shows one of the clearest differences between the R and Python results (<a href="#fig-r-afinn_avg_sentiment">Figure&nbsp;9</a> and <a href="#fig-lexicon-old-afinn_avg_sentiment">Figure&nbsp;10</a>). In the R version, some iOS results are negative, especially for Citi, Bank of America, and Chase. In the Python version, most bank-platform combinations become positive, with only Citi on iOS remaining slightly negative. This suggests that the Python version changes the strength of the bank-level interpretation.</p>
<div class="quarto-layout-panel" data-fig-pos="H">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-r-afinn_avg_sentiment" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="plots/r_afinn_avg_sentiment_bank_platform.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;9: Average AFINN Sentiment by Bank and Platform in R</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-lexicon-old-afinn_avg_sentiment" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="plots/old_lexicon_afinn_avg_sentiment_bank_platform.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;10: Average AFINN Sentiment by Bank and Platform in Python</figcaption>
</figure>
</div>
</div>
</div>
</div>
<p><strong>NRC Sentiment Analysis</strong></p>
<p>Both versions show the same overall ranking of NRC emotion categories (<a href="#fig-r-nrc_emotion">Figure&nbsp;11</a> and <a href="#fig-lexicon-old-nrc_emotion">Figure&nbsp;12</a>). In both R and Python, <em>positive</em> is the most common category, followed by <em>trust</em>. The categories <em>negative</em>, <em>anticipation</em>, and <em>joy</em> also remain important in both versions, while <em>disgust</em> appears the least often.</p>
<p>However, the Python plot shows higher counts overall. For example, positive NRC matches increased from 5,809 in R to 6,852 in Python, and trust increased from 4,417 to 5,160. Therefore, this result can be considered reproducible in terms of the general category ranking, but not in terms of the exact values.</p>
<div class="quarto-layout-panel" data-fig-pos="H">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-r-nrc_emotion" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="plots/r_nrc_emotion_distriution.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;11: Distribution of NRC Emotion Categories in R</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-lexicon-old-nrc_emotion" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="plots/old_lexicon_nrc_emotion_distribution.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;12: Distribution of NRC Emotion Categories in Python</figcaption>
</figure>
</div>
</div>
</div>
</div>
<p><strong>Bigrams</strong></p>
<p>Both versions show that <em>customer service</em> is the most frequent bigram (<a href="#fig-r-bigrams">Figure&nbsp;13</a> and <a href="#fig-lexicon-old-bigrams">Figure&nbsp;14</a>). This means that customer service remains one of the main themes in mobile banking reviews in both R and Python. Other important phrases, such as <em>credit card</em>, <em>user friendly</em>, <em>savings account</em>, and <em>dark mode</em>, also appear in both versions. Therefore, the main topic-level findings were reproduced.</p>
<p>However, the Python plot includes additional bigrams such as <em>don t</em>, <em>doesn t</em>, <em>won t</em>, and <em>t work</em>. These phrases come from contractions being split during tokenization. In the R version, contractions were handled differently, so these forms are less visible in the top bigrams.</p>
<div class="quarto-layout-panel" data-fig-pos="H">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-r-bigrams" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="plots/r_bigrams_top_20.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;13: Top 20 Most Frequent Bigrams in R</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-lexicon-old-bigrams" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="plots/old_lexicon_bigrams_top_20.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;14: Top 20 Most Frequent Bigrams in Python</figcaption>
</figure>
</div>
</div>
</div>
</div>
<p><strong>Quantifying Negation Effect</strong></p>
<p>The plot shows that negation has the strongest effect on lower-rated reviews (<a href="#fig-r-negation">Figure&nbsp;15</a> and <a href="#fig-lexicon-old-negation">Figure&nbsp;16</a>). In both R and Python, 1-star and 2-star reviews receive the largest negative correction. The Python plot shows a stronger negative correction than the R plot, especially for 1-star and 2-star reviews. For higher-rated reviews, the negation effect is much smaller.</p>
<div class="quarto-layout-panel" data-fig-pos="H">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-r-negation" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="plots/r_average_negation_sentiment.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;15: Average Negation-Induced Sentiment Correction by Star Rating in R</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-lexicon-old-negation" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="plots/old_lexicon_average_negation_sentiment.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;16: Average Negation-Induced Sentiment Correction by Star Rating in Python</figcaption>
</figure>
</div>
</div>
</div>
</div>
<p><strong>Comparing Unigram vs Bigram with Negation</strong></p>
<p>Both versions show the same general pattern: reviews with lower star ratings have more negative sentiment scores, while reviews with higher star ratings have more positive scores (<a href="#fig-r-overall">Figure&nbsp;17</a> and <a href="#fig-lexicon-overall">Figure&nbsp;18</a>). However, the Python plot shows a stronger negation effect than the R plot. The difference between unigram sentiment and bigram-adjusted sentiment is larger in Python, especially for low-rated reviews. For higher-rated reviews, both R and Python show a smaller difference between unigram and bigram sentiment.</p>
<div class="quarto-layout-panel" data-fig-pos="H">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-r-overall" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="plots/r_overall_sentiment.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;17: Comparison of Unigram and Bigram Sentiment Scores with Negation Handling in R</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-lexicon-overall" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="plots/old_lexicon_overall_sentiment.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;18: Comparison of Unigram and Bigram Sentiment Scores with Negation Handling in Python</figcaption>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="results-old-data-vs-new-data---lexicon-analysis" class="level2">
<h2 class="anchored" data-anchor-id="results-old-data-vs-new-data---lexicon-analysis">4.2 Results Old Data vs New Data - Lexicon Analysis</h2>
<p>This section compares lexicon-based sentiment results across three lexicons (Bing, AFINN, NRC) between the original 2025 dataset and the newly scraped 2026 dataset. The new dataset contains <strong>4,478 reviews</strong>, covering the same five banks and two platforms but a different temporal window.</p>
<p><strong><em>BING</em></strong></p>
<p>In the new data, the Bing lexicon identified <strong>7,363 positive</strong> and <strong>3,657 negative</strong> word tokens, yielding an overall positive-to-negative ratio of approximately 2.01:1. The directional pattern of results is consistent with the original study: positive words dominate in aggregate, and the platform gap observed in the old data persists — Android reviews skew more positive than iOS reviews across most banks (<a href="#fig-bing-word-new-pf">Figure&nbsp;19</a> and <a href="#fig-bing-word-new-bank">Figure&nbsp;20</a>).</p>
<div id="fig-bing-word-new-pf" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="plots/bing_new_wordnplatform.png" class="img-fluid figure-img" style="width:90.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;19: Top BING sentiment words by platform — new dataset</figcaption>
</figure>
</div>
<div id="fig-bing-word-new-bank" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="plots/bing_new_wordnbank.png" class="img-fluid figure-img" style="width:90.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;20: Top BING sentiment words by bank — new dataset</figcaption>
</figure>
</div>
<p><strong><em>AFINN</em></strong></p>
<p>The AFINN analysis of the new data yields a Pearson correlation between review-level AFINN sum scores and star ratings of <strong>r = 0.539</strong> (n = 3,885; 95% CI: [0.516, 0.561]; p &lt; 0.001). This is a moderate-to-strong positive correlation, confirming that higher AFINN scores correspond to higher user ratings — the same directional conclusion as the original data.</p>
<p>Compared to the old dataset, the correlation in the new data is <strong>slightly lower</strong> (the original study reported a Pearson correlation at 0.59). This small reduction in predictive alignment may reflect the greater temporal concentration of recent reviews around extreme ratings (1 and 5 stars), which inflates the role of polarity extremes and reduces mid-range discrimination.</p>
<p>The per-bank AFINN mean-sum scores reveal an interesting structural shift (<a href="#fig-afinn-bank-new">Figure&nbsp;33</a>): <strong>Citi iOS</strong> is the only bank–platform cell with a <em>negative</em> mean AFINN sum score (−0.724). All other bank–platform cells remain positive. <strong>Wells Fargo iOS</strong> posts the highest mean AFINN sum (3.80) in the new data, followed by <strong>Marcus by Goldman Sachs iOS</strong> (3.12) and <strong>Chase iOS</strong> (2.99). On Android, scores are more tightly clustered, ranging from approximately 1.9 (Chase) to 2.6 (Citi Android), which is broadly consistent with the old data.</p>
<div id="fig-afinn-bank-new" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="plots/afin_bank_new.png" class="img-fluid figure-img" style="width:90.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;21: Average AFINN sentiment by bank and platform — new dataset</figcaption>
</figure>
</div>
<p><strong><em>NRC Emotion</em></strong> The NRC emotion profile in the new data is dominated by <strong>positive</strong> (6,941 tokens) and <strong>trust</strong> (5,281 tokens), together accounting for over 44% of all matched tokens — a pattern that mirrors the old data and is consistent with the service-oriented nature of banking apps, where trust vocabulary (<em>account</em>, <em>recommend</em>, <em>secure</em>) is naturally frequent.</p>
<p>The platform breakdown reveals a structurally important asymmetry (<a href="#fig-nrc-dist">Figure&nbsp;22</a>): Android reviews show a markedly higher <em>positive</em> proportion (26.9% of tokens) compared to iOS (23.8%), while iOS shows higher <em>negative</em> (12.8% vs 9.8%), <em>anger</em> (5.9% vs 4.5%), <em>fear</em> (5.4% vs 3.8%), and <em>sadness</em> (5.7% vs 3.8%) proportions. This Android–iOS emotional gap is consistent across both datasets and reinforces the finding from the BERT analysis that Android users express systematically more positive sentiment than iOS users — a pattern that warrants further investigation into whether it reflects genuine experience differences or platform-specific reviewer demographics.</p>
<div id="fig-nrc-dist" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="plots/nrc_new_distribution.png" class="img-fluid figure-img" style="width:90.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;22: Distribution of NRC emotion composition by platform — new dataset</figcaption>
</figure>
</div>
<p><strong><em>Bigram and Negation Analysis</em></strong></p>
<p>The top bigrams in the new data are largely consistent with the old data: <em>customer service</em>, <em>credit card</em>, <em>user friendly</em>, <em>savings account</em>, and <em>checking account</em> dominate the co-occurrence table. Two new entries — <em>dark mode</em> (rank 13) and <em>blank screen</em> (rank 16) — suggest that UI/UX concerns specific to the late 2025 to early 2026 period have increased in salience.</p>
<p>The negation correction analysis confirms the structural finding from the original study: 1-star reviews show the largest total negation shift (−216 across the dataset, averaging −0.164 per review), reflecting that negative reviews contain the most negator–sentiment bigrams. Crucially, the sign of the correction is <em>negative</em> for 1–4 star reviews but <em>positive</em> for 5-star reviews (total shift +63), meaning that naive unigram AFINN systematically underestimates negativity in low-rated reviews and underestimates positivity in top-rated reviews. This directional finding holds in both the old and new data, confirming that negation correction is not a temporal artifact but a structural property of this type of review language.</p>
<p>The most frequent negated bigrams are <em>no problems</em> (16 occurrences, flipped from −2 to +2), <em>not allow</em> (15), <em>not happy</em> (12), <em>no problem</em> (11), and <em>no help</em> (10) - indicating that both false-negative corrections (e.g., <em>not happy</em> correctly flipped to negative) and false-positive corrections (e.g., <em>no problems</em> correctly flipped to positive) are present in meaningful quantities, broadly consistent with the pattern in the original data.</p>
</section>
<section id="comparison-of-bert-sentiment-results-across-preprocessing-approaches" class="level2">
<h2 class="anchored" data-anchor-id="comparison-of-bert-sentiment-results-across-preprocessing-approaches">4.3 Comparison of BERT Sentiment Results Across Preprocessing Approaches</h2>
<p>This section compares the outputs of the BERT-based sentiment classifier <code>(nlptown/bert-base-multilingual-uncased-sentiment)</code> applied to two versions of the dataset: one preprocessed using the original pipeline and one using the revised approach. Both versions were scored using identical model settings and scoring logic, with predicted star ratings mapped to a normalized sentiment score in the range [0, 1]. The comparison focuses on whether the revised preprocessing affects the distribution of predicted sentiment, its alignment with actual star ratings, and the relative sentiment profiles across banks and platforms.</p>
<p><strong>Distribution of BERT Predicted Sentiment</strong></p>
<p>Both datasets produce a broadly similar bimodal distribution of BERT-predicted sentiment, with the majority of reviews classified at either the negative extreme (1 star) or the positive extreme (5 stars), and relatively few reviews falling in the middle ratings of 2 through 4 (<a href="#fig-bert-dist-old">Figure&nbsp;23</a> and <a href="#fig-bert-dist-new">Figure&nbsp;24</a>). However, a notable difference emerges in the balance between the two poles. In the older data, the 1-star predicted count (~1,550) is considerably closer to the 5-star predicted count (~2,000), whereas in the newer data the gap widens, with 1-star predictions declining to approximately 1,380 while 5-star predictions rise to around 2,100 (<a href="#fig-bert-dist-new">Figure&nbsp;24</a>). This suggests that the newer batch of reviews contains a higher proportion of positively-perceived content as classified by the model. The sentiment score density plots reinforce this pattern: both distributions are heavily concentrated at 0.0 and 1.0, reflecting the model’s tendency toward confident polar predictions, with the overall shape of the density curve remaining consistent across both datasets (<a href="#fig-bert-dist-old">Figure&nbsp;23</a> and <a href="#fig-bert-dist-new">Figure&nbsp;24</a>).</p>
<div id="fig-bert-dist-old" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="plots/bert_old_distribution.png" class="img-fluid figure-img" style="width:90.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;23: Distribution of BERT predicted star ratings and sentiment scores — older dataset</figcaption>
</figure>
</div>
<div id="fig-bert-dist-new" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="plots/bert_new_distribution.png" class="img-fluid figure-img" style="width:90.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;24: Distribution of BERT predicted star ratings and sentiment scores — newer dataset</figcaption>
</figure>
</div>
<p><strong>Relationship Between BERT Scores and Actual Star Ratings</strong></p>
<p>The relationship between BERT sentiment scores and actual star ratings is consistent across both datasets (<a href="#fig-bert-box-old">Figure&nbsp;25</a> and <a href="#fig-bert-box-new">Figure&nbsp;31</a>). In both cases, the model assigns near-zero sentiment scores to 1-star reviews with very tight interquartile ranges, indicating high confidence in negative classifications. Scores rise progressively through 2- and 3-star ratings, with 3-star reviews showing the widest spread, reflecting the model’s uncertainty around neutral or mixed-sentiment reviews. Reviews rated 4 and 5 stars are predominantly scored above the neutral threshold of 0.5, with 5-star reviews showing a highly compressed distribution concentrated at 1.0. The two datasets are visually near-identical in this regard (<a href="#fig-bert-box-old">Figure&nbsp;25</a> and <a href="#fig-bert-box-new">Figure&nbsp;31</a>), suggesting that the shift in review composition between the older and newer data did not meaningfully alter the model’s ability to align predicted sentiment with actual star ratings.</p>
<div id="fig-bert-box-old" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="plots/bert_old_sentiment_score_boxplot.png" class="img-fluid figure-img" style="width:90.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;25: BERT sentiment score by star rating — older dataset</figcaption>
</figure>
</div>
<div id="fig-bert-box-new" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="plots/bert_new_sentiment_score_boxplot.png" class="img-fluid figure-img" style="width:90.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;26: BERT sentiment score by star rating — newer dataset</figcaption>
</figure>
</div>
<p><strong>Average BERT Sentiment Scores by Bank and Platform</strong></p>
<p>Across both datasets, a consistent platform gap is visible: Android reviews tend to receive higher BERT sentiment scores than iOS reviews for most banks (<a href="#fig-bert-bank-old">Figure&nbsp;27</a> and <a href="#fig-bert-bank-new">Figure&nbsp;32</a>). Citi stands out in both periods, with Android scores approaching 0.9 while iOS scores remain well below the neutral threshold of 0.5, making it the most polarised bank by platform in both the older and newer data. Bank of America shows a similar pattern, with strong Android sentiment but iOS scores falling below neutral in both datasets. Wells Fargo is the only bank where both platforms consistently score above neutral, and remains so across both periods. One notable structural difference between the two datasets is that Chase appears in the older data (<a href="#fig-bert-bank-old">Figure&nbsp;27</a>) with both platforms scoring above neutral, whereas in the newer data (<a href="#fig-bert-bank-new">Figure&nbsp;32</a>) Chase drops to the bottom of the ranking with iOS sentiment just at the neutral threshold. Marcus by Goldman Sachs remains relatively stable across both periods, with Android scores moderately above neutral and iOS scores hovering near 0.5.</p>
<div id="fig-bert-bank-old" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="plots/bert_old_banknplatform.png" class="img-fluid figure-img" style="width:90.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;27: Average BERT sentiment score by bank and platform — older dataset</figcaption>
</figure>
</div>
<div id="fig-bert-bank-new" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="plots/bert_new_banknplatform.png" class="img-fluid figure-img" style="width:90.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;28: Average BERT sentiment score by bank and platform — newer dataset</figcaption>
</figure>
</div>
<p><strong>Average BERT Sentiment Scores by Operating Platform</strong></p>
<p>The per-platform breakdown of BERT sentiment scores by star rating reveals a largely stable pattern across both datasets (<a href="#fig-bert-plat-old">Figure&nbsp;29</a> and <a href="#fig-bert-plat-new">Figure&nbsp;30</a>). On Android, both the older and newer data show near-identical distributions: 1-star reviews are tightly concentrated at 0.0, scores rise progressively through 2 and 3 stars with widening spread, and 4- and 5-star reviews sit predominantly above the neutral threshold. The iOS platform tells a slightly different story between the two periods. In the older data (<a href="#fig-bert-plat-old">Figure&nbsp;29</a>), the iOS 4-star distribution closely mirrors its Android counterpart, with a median around 0.75. In the newer data (<a href="#fig-bert-plat-new">Figure&nbsp;30</a>), the iOS 4-star box shifts noticeably, with a lower median of approximately 0.6 and a wider interquartile range, suggesting greater variability in how the model scores moderately positive iOS reviews in the newer period. Across both datasets and platforms, 1- and 2-star distributions remain consistently low and 5-star reviews remain compressed near 1.0, indicating that the model’s confidence at the sentiment extremes is robust regardless of platform or time period.</p>
<div id="fig-bert-plat-old" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="plots/bert_old_per_platform.png" class="img-fluid figure-img" style="width:90.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;29: BERT sentiment score by star rating per platform — older dataset</figcaption>
</figure>
</div>
<div id="fig-bert-plat-new" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="plots/bert_new_per_platform.png" class="img-fluid figure-img" style="width:90.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;30: BERT sentiment score by star rating per platform — newer dataset</figcaption>
</figure>
</div>
<p><strong>Statistical Correlation Between BERT Scores and Star Ratings</strong></p>
<table class="table">
<thead>
<tr class="header">
<th>Metric</th>
<th>Old Data</th>
<th>New Data</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>n</td>
<td>4,518</td>
<td>4,478</td>
</tr>
<tr class="even">
<td>Pearson r</td>
<td>0.8615</td>
<td>0.8660</td>
</tr>
<tr class="odd">
<td>p-value</td>
<td>&lt; 0.001</td>
<td>&lt; 0.001</td>
</tr>
<tr class="even">
<td>95% CI</td>
<td>[0.8538, 0.8688]</td>
<td>[0.8585, 0.8731]</td>
</tr>
</tbody>
</table>
<p>Both datasets show a strong positive correlation between BERT sentiment scores and actual star ratings, with Pearson r values of 0.8615 and 0.8660 for the older and newer data respectively, both statistically significant (p &lt; 0.001). The marginal increase in r across the two periods suggests a slightly stronger alignment between model-predicted sentiment and user-assigned ratings in the newer dataset, though the difference is negligible given the overlapping confidence intervals ([0.8538, 0.8688] vs [0.8585, 0.8731]). Overall, these results confirm that the BERT model captures sentiment signal consistently across both time periods.</p>
<p><strong>Statistical Correlation Between BERT Scores and Users’ Platforms</strong></p>
<table class="table">
<thead>
<tr class="header">
<th>Metric</th>
<th>Old Data</th>
<th>New Data</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Platforms compared</td>
<td>Android vs iOS</td>
<td>Android vs iOS</td>
</tr>
<tr class="even">
<td>U statistic</td>
<td>3,379,410.0000</td>
<td>3,174,169.0000</td>
</tr>
<tr class="odd">
<td>p-value</td>
<td>3.23e-93</td>
<td>1.46e-63</td>
</tr>
</tbody>
</table>
<p>Both datasets show a statistically significant difference in BERT sentiment scores between Android and iOS platforms (p &lt; 0.001 in both cases), confirming that platform is a meaningful source of variation in user sentiment regardless of time period. The U statistic is larger in the older data (3,379,410 vs 3,174,169), which is consistent with the older dataset having slightly more observations (n = 4,518 vs 4,478). While both p-values are extremely small, the older data yields a more extreme test statistic, suggesting the platform gap in sentiment may have been marginally more pronounced in the earlier period, which aligns with what was observed in the bank-by-platform plots (<a href="#fig-bert-bank-old">Figure&nbsp;27</a> and <a href="#fig-bert-bank-new">Figure&nbsp;32</a>).</p>
</section>
<section id="comparison-of-afinn-and-bert-sentiment-new-data" class="level2">
<h2 class="anchored" data-anchor-id="comparison-of-afinn-and-bert-sentiment-new-data">4.4 Comparison of AFINN and BERT Sentiment — New Data</h2>
<p>This section compares the outputs of the AFINN lexicon-based model and the BERT-based sentiment classifier (<code>nlptown/bert-base-multilingual-uncased-sentiment</code>) applied to the newer dataset. AFINN assigns integer scores (−5 to +5) to matched tokens and aggregates them at the review level, while BERT predicts a 1–5 star rating from full review text, normalised to a sentiment score in [0, 1]. The comparison focuses on validity against actual star ratings, score distributions, and sentiment profiles across banks and platforms.</p>
<p><strong>Distribution of Predicted Sentiment</strong></p>
<p>The two models produce structurally different distributions. AFINN sum scores are unimodal and centred near zero, with a continuous range driven by review length and word count variation. BERT scores are strongly bimodal, with sharp density spikes at 0 - 1, reflecting the model’s tendency to assign confident polar predictions (<a href="#fig-bert-box-new">Figure&nbsp;31</a>). AFINN therefore captures gradations of sentiment intensity across a wide unbounded scale, while BERT tends to classify reviews as clearly positive or clearly negative with little ambiguity in between.</p>
<p>A secondary structural difference is coverage: AFINN matched scored tokens in 86.8% of reviews, leaving 13.2% unscored due to out-of-vocabulary words. BERT scores all 4,478 reviews without missing values, as it operates on full review text rather than word-by-word lexicon lookup.</p>
<p><strong>Relationship Between Sentiment Scores and Actual Star Ratings</strong></p>
<p>Both models produce sentiment scores that increase monotonically with star ratings, confirming convergent validity. However, BERT outperforms AFINN in alignment with user-assigned ratings. AFINN achieves a Pearson correlation of r = 0.539, while BERT achieves r = 0.866 — a difference of 0.33 correlation points, reflecting BERT’s capacity to capture contextual meaning beyond individual word scores.</p>
<p>Boxplots by star rating reveal a shared weakness at the 3-star midpoint: for genuinely mixed reviews, both AFINN and BERT show high variance and overlap with adjacent star categories. Neither model reliably distinguishes neutral sentiment from mildly positive or mildly negative reviews.</p>
<div id="fig-bert-box-new" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="plots/bert_new_sentiment_score_boxplot.png" class="img-fluid figure-img" style="width:90.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;31: BERT sentiment score by star rating — newer dataset</figcaption>
</figure>
</div>
<p><strong>Average Sentiment Scores by Bank and Platform</strong></p>
<p>Both models agree on the direction of cross-bank sentiment differences in most cases. The strongest point of agreement is Wells Fargo iOS, which ranks highest under both models, and Citi iOS, which ranks lowest under both (AFINN mean_sum = −0.72, the only negative cell across all bank–platform combinations; BERT score ≈ 0.15).</p>
<p>The Citi platform is the most striking finding shared by both models: Citi Android reviews score positively under AFINN (mean_sum = 2.62) and very highly under BERT (≈ 0.90), while Citi iOS reviews are rated negatively by AFINN and near-zero by BERT. The magnitude of this divergence is more extreme under BERT.</p>
<p>For Bank of America, both models find Android reviews more positive than iOS, with the gap amplified under BERT. For Chase and Marcus by Goldman Sachs, both models find iOS reviews slightly more positive than Android (Chase AFINN: 2.99 vs 1.93; Chase BERT: ≈ 0.62 vs ≈ 0.59; Marcus AFINN: 3.12 vs 2.46; Marcus BERT: ≈ 0.50 vs ≈ 0.60), with consistent direction and small absolute differences.</p>
<div id="fig-bert-bank-new" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="plots/bert_new_banknplatform.png" class="img-fluid figure-img" style="width:90.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;32: Average BERT sentiment score by bank and platform — newer dataset</figcaption>
</figure>
</div>
<div id="fig-afinn-bank-new" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="plots/AFINN_new_sentiment_barchart.png" class="img-fluid figure-img" style="width:90.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;33: Average AFINN sentiment score by bank and platform — newer dataset</figcaption>
</figure>
</div>
<p><strong>Summary</strong></p>
<table class="table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Dimension</th>
<th>AFINN</th>
<th>BERT</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Correlation with star rating</td>
<td>r = 0.539</td>
<td>r = 0.866</td>
</tr>
<tr class="even">
<td>95% CI</td>
<td>[0.516, 0.561]</td>
<td>[0.859, 0.873]</td>
</tr>
<tr class="odd">
<td>Review coverage</td>
<td>86.8% (3,885 / 4,478)</td>
<td>100% (4,478 / 4,478)</td>
</tr>
<tr class="even">
<td>Score distribution</td>
<td>Unimodal, centred near 0</td>
<td>Bimodal, peaks at 0 and 1</td>
</tr>
<tr class="odd">
<td>3-star reviews</td>
<td>High variance, unreliable</td>
<td>High variance, unreliable</td>
</tr>
<tr class="even">
<td>Citi iOS</td>
<td>−0.72 (only negative cell)</td>
<td>≈ 0.15 (lowest cell)</td>
</tr>
<tr class="odd">
<td>Wells Fargo iOS</td>
<td>3.80 (highest cell)</td>
<td>≈ 0.95 (highest cell)</td>
</tr>
<tr class="even">
<td>Platform direction agreement</td>
<td>—</td>
<td>Consistent across all banks</td>
</tr>
</tbody>
</table>
<p>Both models consistently identify the same outlier patterns — Citi’s platform asymmetry and Wells Fargo iOS’s high sentiment — suggesting these findings are robust to method choice. Where they diverge most is in resolving ambiguous mid-range reviews and in overall alignment with star ratings, where BERT’s higher correlation (r = 0.866 vs 0.539) and full coverage make it the more reliable instrument for this dataset.</p>
</section>
</section>
<section id="discussion" class="level1">
<h1>5 Discussion</h1>
<section id="reproducibility-assessment" class="level2">
<h2 class="anchored" data-anchor-id="reproducibility-assessment">5.1 Reproducibility Assessment</h2>
<p>The R-to-Python reproduction was successful when interpreting the main conclusions, but the numerical results were not identical. In both versions, the same general patterns appeared. Positive sentiment was more common than negative sentiment, higher star ratings were linked to higher sentiment scores, Android reviews were usually more positive than iOS reviews, and negation correction had the strongest effect on low-rated reviews. However, some differences were expected due to a different programming environment. The Python version used different packages than R.</p>
<p>The R-to-Python translation demonstrates that the core analytical conclusions of the original study are reproducible across languages. Minor numerical differences arise from:</p>
<ul>
<li><strong>Language detection:</strong> <code>langdetect</code> vs <code>cld3</code> use different underlying models; the set of English-classified reviews may differ slightly</li>
<li><strong>Stopword lists:</strong> <code>tidytext::stop_words</code> differs from NLTK’s English list</li>
<li><strong>Bing lexicon size:</strong> NLTK <code>opinion_lexicon</code> covers more words than the Bing lexicon embedded in tidytext</li>
</ul>
<p>These are expected cross-language reproducibility gaps and do not undermine the directional conclusions.</p>
</section>
<section id="limitations" class="level2">
<h2 class="anchored" data-anchor-id="limitations">5.2 Limitations</h2>
<ul>
<li><strong>Lexicon domain mismatch:</strong> all three lexicons were built for general English, not financial app reviews; domain terms like <em>overdraft</em>, <em>Zelle</em>, and <em>wire transfer</em> are likely absent, leaving financially-specific sentiment unscored.</li>
<li><strong>Negation scope:</strong> the bigram correction only handles two-word negation windows; longer-range constructions like <em>I can no longer trust this app</em> are not captured.</li>
<li><strong>Temporal confounding:</strong> the two datasets cover different time windows, so observed sentiment differences may reflect app updates or service changes rather than stable bank-level properties.</li>
<li><strong>Non-representative sampling:</strong> both scrapers return reviews ordered by recency, not randomly, introducing recency bias and over-representing users who review immediately after major updates or outages.</li>
<li><strong>Text sparsity in old data:</strong> the older dataset has a median review length of 0 words, meaning the majority of observations carry no text; token-level sentiment analysis operates on a small, potentially non-representative subset.</li>
<li><strong>Label imbalance:</strong> both datasets skew heavily toward 1-star and 5-star ratings, leaving 3-star neutral reviews underrepresented, consistent with the high variance observed at the midpoint under both models.</li>
<li><strong>BERT domain mismatch:</strong> the <code>nlptown</code> model was fine-tuned on general product reviews, not banking app reviews specifically; banking-specific language may fall outside its training distribution.</li>
<li><strong>Lack of human validation:</strong> no manual annotation was performed to validate the sentiment classifications or to identify domain-specific sentiment expressions that may be missed by lexicon or model-based approaches.</li>
</ul>
</section>
</section>
<section id="generative-ai-disclosure" class="level1">
<h1>6 Generative AI Disclosure</h1>
<p>In accordance with course policy (dr Jakub Michańków, Reproducible Research 2026), generative AI (Claude AI) was used to assist with coding tasks, refine the code.</p>
<p>All analytical decisions, interpretations, and research design are the team’s own work.</p>
</section>
<section id="references" class="level1">
<h1>References</h1>
<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-mohammad2013crowdsourcing" class="csl-entry" role="listitem">
Mohammad, Saif M., and Peter D. Turney. 2013. <span>“Crowdsourcing a Word-Emotion Association Lexicon.”</span> In <em>Computational Intelligence</em>, 29:436–65. 3. Wiley.
</div>
<div id="ref-nielsen2011new" class="csl-entry" role="listitem">
Nielsen, Finn Årup. 2011. <span>“A New <span>ANEW</span>: Evaluation of a Word List for Sentiment Analysis in Microblogs.”</span> <a href="https://arxiv.org/abs/1103.2903">https://arxiv.org/abs/1103.2903</a>.
</div>
<div id="ref-nlptown2019" class="csl-entry" role="listitem">
NLP Town. 2019. <span>“Bert-Base-Multilingual-Uncased-Sentiment.”</span> Hugging Face. <a href="https://doi.org/10.57967/hf/1515">https://doi.org/10.57967/hf/1515</a>.
</div>
<div id="ref-silge2017text" class="csl-entry" role="listitem">
Silge, Julia, and David Robinson. 2017. <em>Text Mining with r: A Tidy Approach</em>. O’Reilly Media. <a href="https://www.tidytextmining.com/">https://www.tidytextmining.com/</a>.
</div>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>